version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  php:
    container_name: php-fpm
    build:
      context: ./docker/php-fpm
    depends_on:
      - db
    volumes:
      - ./:/src
    command: /src/docker/install.sh
    ports:
      - 8000:8000
volumes:
  db:
    driver: local